"""Open Data Products Python SDK.

This package provides Python support for the OpenDataProducts.org standards
family. Each standard lives in its own namespace:

- :mod:`open_data_products.odps`
- :mod:`open_data_products.odpc`
- :mod:`open_data_products.odpg`
- :mod:`open_data_products.odpv`
"""

# flake8: noqa: E402

__version__ = "0.3.2"
version = __version__

from . import odpc
from . import odpg
from . import odpr
from . import odps
from . import odpv
from .agent import (
    detect_document,
    explain_document,
    explain_product,
    explain_vocabulary,
    load_document,
    resolve_references,
    validate_document,
)
from .contracts import (
    AlignmentFinding,
    ContractDocument,
    ContractExportResult,
    ContractReference,
    ContractSchemaField,
    ContractSchemaModel,
    ContractSchemaSummary,
    ContractSummary,
    ContractToolAvailability,
    ContractValidationResult,
    Finding,
    ProductContractAlignmentResult,
    ProductContractReport,
    check_product_contract_alignment,
    detect_datacontract_cli,
    explain_contract,
    export_contract,
    extract_contract_schema,
    extract_contract_schema_from_document,
    generate_product_contract_report,
    load_contract,
    resolve_product_contracts,
    summarize_contract,
    summarize_contract_document,
    validate_contract,
)
from .generation import (
    anthropic_generate,
    copy_config_template,
    copy_generation_prompts,
    create_generation_client,
    ensure_ollama_model,
    generate_local_artifact,
    generate_local_artifacts_for_kind,
    generate_local_artifacts,
    get_config,
    get_config_path,
    load_generation_config,
    list_ollama_models,
    list_generation_prompts,
    llama_cpp_generate,
    load_generation_prompt,
    openai_chat_generate,
    openai_generate,
    print_config,
    render_generation_prompt,
    resolve_generation_settings,
    validate_config,
)
from .odpc import (
    build_catalog,
    build_catalog_artifacts,
    render_catalog_gcf,
    render_catalog_html,
    render_catalog_toon,
    render_catalog_schema_json,
    write_catalog,
    write_catalog_gcf,
    write_catalog_html,
    write_catalog_toon,
    write_catalog_artifacts,
)
from .odpg import (
    build_graph,
    convert_file,
    convert_graph,
    dump_graph_yaml,
    render_graph_gcf,
    render_graph_toon,
    write_graph,
    write_graph_gcf,
    write_graph_toon,
)
from .okf import (
    OkfConcept,
    OkfValidationResult,
    export_okf_bundle,
    import_okf_bundle,
    load_okf_bundle,
    summarize_okf_bundle,
    validate_okf_bundle,
)
from .odpv import (
    agent_vocabulary_context,
    check_vocabulary_relationship,
    explain_vocabulary_term,
    resolve_vocabulary_term,
)
from .pricing import pricing_to_402
from .portfolio import (
    build_portfolio,
    explain_portfolio,
    localize_portfolio,
    refresh_portfolio,
    render_portfolio,
    sync_portfolio,
)
from .resources import get_resource, list_resources
from .odpr import (
    RecipeDocument,
    build_recipe_catalog,
    check_starter_catalog,
    copy_recipe_config_template,
    explain_recipe,
    execute_recipe_run,
    get_recipe_config,
    get_recipe_config_path,
    get_recipe_guidance,
    init_starter_recipe,
    list_recipes,
    list_starter_recipes,
    load_recipe,
    load_recipe_catalog,
    load_recipe_guidance,
    plan_recipe_run,
    print_recipe_config,
    resolve_starter_recipe,
    search_recipe_guidance,
    validate_recipe,
    validate_recipe_config,
    validate_odpr_document,
    write_recipe_catalog,
)
from .results import Reference, Resource, ValidationResult
from .summary import load_summary

__all__ = [
    "__version__",
    "version",
    "odpc",
    "odpg",
    "odpr",
    "odps",
    "odpv",
    "OkfConcept",
    "OkfValidationResult",
    "Reference",
    "Resource",
    "RecipeDocument",
    "ValidationResult",
    "AlignmentFinding",
    "agent_vocabulary_context",
    "build_catalog",
    "build_catalog_artifacts",
    "build_graph",
    "build_portfolio",
    "build_recipe_catalog",
    "check_starter_catalog",
    "check_vocabulary_relationship",
    "convert_file",
    "convert_graph",
    "ContractToolAvailability",
    "ContractValidationResult",
    "ContractDocument",
    "ContractExportResult",
    "ContractReference",
    "ContractSchemaField",
    "ContractSchemaModel",
    "ContractSchemaSummary",
    "ContractSummary",
    "Finding",
    "ProductContractAlignmentResult",
    "ProductContractReport",
    "check_product_contract_alignment",
    "detect_document",
    "detect_datacontract_cli",
    "dump_graph_yaml",
    "explain_contract",
    "export_contract",
    "export_okf_bundle",
    "extract_contract_schema",
    "extract_contract_schema_from_document",
    "explain_document",
    "explain_product",
    "explain_portfolio",
    "explain_vocabulary_term",
    "explain_vocabulary",
    "execute_recipe_run",
    "get_resource",
    "list_resources",
    "localize_portfolio",
    "load_document",
    "load_contract",
    "load_summary",
    "load_okf_bundle",
    "load_recipe",
    "load_recipe_guidance",
    "list_generation_prompts",
    "load_generation_prompt",
    "pricing_to_402",
    "import_okf_bundle",
    "generate_product_contract_report",
    "anthropic_generate",
    "copy_config_template",
    "copy_generation_prompts",
    "copy_recipe_config_template",
    "create_generation_client",
    "explain_recipe",
    "ensure_ollama_model",
    "generate_local_artifact",
    "generate_local_artifacts_for_kind",
    "generate_local_artifacts",
    "get_config",
    "get_config_path",
    "get_recipe_config",
    "get_recipe_config_path",
    "get_recipe_guidance",
    "init_starter_recipe",
    "load_generation_config",
    "list_ollama_models",
    "list_recipes",
    "list_starter_recipes",
    "load_recipe_catalog",
    "openai_chat_generate",
    "openai_generate",
    "print_config",
    "print_recipe_config",
    "search_recipe_guidance",
    "render_catalog_gcf",
    "render_catalog_html",
    "render_catalog_toon",
    "render_catalog_schema_json",
    "render_generation_prompt",
    "refresh_portfolio",
    "render_portfolio",
    "plan_recipe_run",
    "resolve_starter_recipe",
    "resolve_generation_settings",
    "sync_portfolio",
    "validate_config",
    "validate_recipe",
    "validate_recipe_config",
    "validate_odpr_document",
    "write_recipe_catalog",
    "write_graph",
    "render_graph_gcf",
    "render_graph_toon",
    "resolve_references",
    "resolve_vocabulary_term",
    "resolve_product_contracts",
    "summarize_contract",
    "summarize_contract_document",
    "summarize_okf_bundle",
    "validate_contract",
    "validate_document",
    "validate_okf_bundle",
    "write_catalog",
    "write_catalog_gcf",
    "write_catalog_html",
    "write_catalog_toon",
    "write_catalog_artifacts",
    "write_graph_gcf",
    "write_graph_toon",
]
